config/routes.rb
Rails.application.routes.draw do
  root 'flights#index'
  get '/result',  to: 'static_pages#result'
  get '/about',   to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
  get '/signup',  to: 'users#new'
  resources :users
  resources :flights do
    resources :transactions
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flight.rb
class Flight < ApplicationRecord
  has_many :transactions
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :flight
end

app/models/user.rb
class User < ApplicationRecord
    before_save { self.email = email.downcase }
    validates :name, presence: true, length: { maximum: 50 }
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, length: { maximum: 255 },
                format: { with: VALID_EMAIL_REGEX },
                uniqueness: { case_sensitive: false}
    has_secure_password
    validates :password, presence: true, length: { minimum: 6 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
  include FlightsHelper

  def index
    @flights = Flight.all
  end

  def new
    @flight = Flight.new
  end

  def create
    @flight = Flight.new(flight_params)
    @flight.save
    flash.notice = "Flight to '#{@flight.destination}' Created!"
    redirect_to flight_path(@flight)
  end

  def show
    @flight = Flight.find(params[:id])
    @environment_key = Rails.configuration.spreedly['environment_key']
    @transaction = Transaction.new
    @transaction.flight_id = @flight.id
  end
end

app/controllers/static_pages_controller.rb
require 'net/http'

class StaticPagesController < ApplicationController
  def home 
  end

  def result
    @payment_token = params[:payment_method_token]
    # build the cURL command mentioned here: https://docs.spreedly.com/basics/purchase/
    purchase_uri = URI("https://core.spreedly.com/v1/gateways/#{Rails.configuration.spreedly['gateway_token']}/purchase.json")
    purchase_post_request = Net::HTTP::Post.new(purchase_uri)
    purchase_post_request.basic_auth(
      Rails.configuration.spreedly['environment_key'],
      Rails.configuration.spreedly['access_secret']
    )
    purchase_post_request['Content-Type'] = 'application/json'
    purchase_post_request.body = {
      'transaction' => {
        'payment_method_token' => @payment_token,
        'amount' => 100,
        'currency_code' => 'USD',
        'retain_on_success' => true
      }
    }.to_json

    purchase_response = Net::HTTP.start(purchase_uri.hostname, purchase_uri.port, use_ssl: true) do |http|
      http.request(purchase_post_request).body
    end
    @parsed_purchase_response = JSON.parse(purchase_response)
  end

  def about
  end

  def contact
  end
end

app/controllers/transactions_controller.rb
require 'net/http'
require 'json'

class TransactionsController < ApplicationController
  include TransactionsHelper

  def index
    @transactions = Transaction.all
  end

  def show
  end

  def new
    @flight = Flight.find(params[:flight_id])
    @transaction = Transaction.new
    @transaction.flight_id = @flight.id
    @environment_key = Rails.configuration.spreedly['environment_key']
    @total_price = @flight.price
    @total_price += 200 if params[:hotel] == 'true'
    
    if params[:payment_method_token]
      payment_token = params[:payment_method_token]
      total_charge = params[:total_charge].to_i
      # build the cURL command mentioned here: https://docs.spreedly.com/basics/purchase/
      purchase_uri = URI("https://core.spreedly.com/v1/gateways/#{Rails.configuration.spreedly['gateway_token']}/purchase.json")
      purchase_post_request = Net::HTTP::Post.new(purchase_uri)

      purchase_post_request.basic_auth(
        Rails.configuration.spreedly['environment_key'],
        Rails.configuration.spreedly['access_secret']
      )

      purchase_post_request['Content-Type'] = 'application/json'
      purchase_post_request.body = {
        'transaction' => {
          'payment_method_token' => payment_token,
          'amount' => @flight.price * 100,
          'currency_code' => 'USD',
          'retain_on_success' => params[:save_card]
        }
      }.to_json

      purchase_response = Net::HTTP.start(purchase_uri.hostname, purchase_uri.port, use_ssl: true) do |http|
        http.request(purchase_post_request).body
      end
      parsed_purchase_response = JSON.parse(purchase_response)
      transaction_token = parsed_purchase_response['transaction']['token']
      @transaction.transaction_token = transaction_token
      @transaction.total_price = @flight.price
      @transaction.save
      flash.notice = "Transaction #{transaction_token} Completed!"

      if total_charge != @flight.price
        pmd_delivery_uri = URI("https://core.spreedly.com/v1/receivers/#{Rails.configuration.spreedly['receiver_token']}/deliver.json")
        pmd_delivery_post_request = Net::HTTP::Post.new(pmd_delivery_uri)

        pmd_delivery_post_request.basic_auth(
          Rails.configuration.spreedly['environment_key'],
          Rails.configuration.spreedly['access_secret']
        )

        pmd_delivery_post_request['Content-Type'] = 'application/json'
        pmd_delivery_post_request.body = {
          'delivery' => {
            'payment_method_token' => payment_token,
            'url' => 'https://spreedly-echo.herokuapp.com',
            'headers' => 'Content-Type: application/json',
            'body' => '{ \"product_id\": \"916598\", \"card_number\": \"{{credit_card_number}}\" }'
          }
        }.to_json

        pmd_delivery_response = Net::HTTP.start(pmd_delivery_uri.hostname, pmd_delivery_uri.port, use_ssl: true) do |http|
          http.request(pmd_delivery_post_request).body
        end
        parsed_pmd_delivery_response = JSON.parse(pmd_delivery_response)
        pmd_transaction_token = parsed_pmd_delivery_response['transaction']['token']
      end 
    end
  
    # redirect_to flight_transaction_path(@flight, @transaction)
  end

  def create
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      # Handle a successful save.
    else
      render 'new'
    end
  end

  private
    def user_params
      params.require(:user).permit(:name, :email, :password, 
                                    :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

	# Returns the full title on a per-page basis.
	def full_title(page_title = '')
		base_title = "Spreedly Airlines Sample App"
		if page_title.empty?
			base_title
		else
			page_title + " | " + base_title
		end
	end
end

app/helpers/flights_helper.rb
module FlightsHelper
  def flight_params
    params.require(:flight).permit(:origin, :destination, :price)
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
  def transaction_params
    params.require(:transaction).permit(:total_price, :transaction_token)
  end
end

app/helpers/users_helper.rb
module UsersHelper
  # Returns the Gravatar for the given user.
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/flights/_transaction.html.erb
<div>
  <h4>Transaction token: <%= transaction.transaction_token %></h4>
  <p class="transaction"><%= transaction.total_price %></p>
</div>

app/views/flights/index.html.erb
<div class="center jumbotron">
  <h2>Available Flights<h2>

  <table>
    <tr>
      <th>Origin  |</th> 
      <th> Destination  |</th> 
      <th> Price  |</th>
      <th> Add $200 Hotel Room?</th>
    </tr>
    <% @flights.each do |flight| %>
    <tr>
      <td><%= flight.origin %></td>
      <td><%= flight.destination %></td>
      <td>$<%= flight.price %></td>
      <td>
        <form action="/flights/<%= flight.id %>/transactions/new" id="payment-form">
            <input type="checkbox" name="hotel" value="true"> >>>>>>>>>>>>>>>   
            <input type="submit" value="Select Flight">
        </form>
      </td>
    </tr>
    <% end %>
  </table>

</div>

app/views/flights/new.html.erb
<h1>Create a New Flight</h1>
 
<%= form_for(@flight) do |f| %>
  <ul>
    <% @flight.errors.full_messages.each do |error| %>
      <li><%= error %></li>
    <% end %>
  </ul>
  <p>
    <%= f.label :origin %><br />
    <%= f.text_field :origin %>
  </p>
  <p>
    <%= f.label :destination %><br />
    <%= f.text_field :destination %>
  </p>
  <p>
    <%= f.label :price %><br />
    <%= f.number_field :price %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/flights/show.html.erb
<div class="center jumbotron">

  <h2>Selected Flight Info:</h2>
  <ul>
    <li>Origin Airport: <%= @flight.origin %></li>
    <li>Destination Airport: <%= @flight.destination %></li>
    <li>Price: $<%= @flight.price %></li>
  </ul>

  <h3>Transactions</h3>
  <%= render partial: 'flights/transaction', collection: @flight.transactions %>
  <%= render partial: 'transactions/form' %>
  <form id="payment-form" action="/flights/<%= @flight.id %>/transactions/create">
    <input type="hidden" name="payment_method_token" id="payment_method_token">
    <input type="hidden" name="full_name" id="full_name">
    <input type="hidden" name="month" id="month">
    <input type="hidden" name="year" id="year">
    <input type="button" value="Enter Payment Info" onclick="SpreedlyExpress.openView();">
  </form>

</div>

<script>
  SpreedlyExpress.init("<%= "#{@environment_key}" %>", {
    "amount": "<%= "$#{@flight.price}" %>",
    "company_name": "Spreedly Airlines",
    "sidebar_top_description": "Confirm Purchase",
    "sidebar_bottom_description": "<%= "#{@flight.origin}" %> to <%= "#{@flight.destination}" %>"
  });

  SpreedlyExpress.onPaymentMethod(function(token, paymentMethod) {

    // Send requisite payment method info to backend
    var tokenField = document.getElementById("payment_method_token");

    tokenField.setAttribute("value", token);

    var masterForm = document.getElementById('payment-form');
    masterForm.submit();
  });

  let handlePaymentToken = function(token, formData) {
    document.getElementById('full_name').value = formData["full_name"]
    document.getElementById('month').value = formData["month"]
    document.getElementById('year').value = formData["year"]
    document.getElementById('payment_method_token').value = token
    document.getElementById('payment-form').submit();
  }
  SpreedlyExpress.onPaymentMethod(handlePaymentToken);

</script>

app/views/layouts/_footer.html.erb
<footer class="footer">
	<small>
		<%# The <a href="https://www.railstutorial.org/">Ruby on Rails Tutorial</a>
		by <a href="http://www.michaelhartl.com/">Michael Hartl</a> %>
	</small>
	<nav>
		<ul>
			
		</ul>
	</nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
	<div class="container">
		<%= link_to "spreedly airlines", root_path, id: "logo" %>
		<nav>
			<ul class="nav navbar-nav navbar-right">
				<li><%= link_to "Transactions",   flight_transactions_path(1) %></li>
				<li><%= link_to "Create a New Flight", new_flight_path %></li>
			</ul>
		</nav>
	</div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
    </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>

  <body>
    <script src="https://core.spreedly.com/iframe/express-2.min.js"></script>
    <%= render 'layouts/header' %>
    <div class="container">
      <p class="flash"><%= flash.notice %></p>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<h1>About</h1>
<p>
  The <a href="https://www.railstutorial.org/"><em>Ruby on Rails
  Tutorial</em></a> is a
  <a href="https://www.railstutorial.org/book">book</a> and
  <a href="http://screencasts.railstutorial.org/">screencast series</a>
  to teach web development with
  <a href="http://rubyonrails.org/">Ruby on Rails</a>.
  This is the sample application for the tutorial.
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>
    Contact the Ruby on Rails Tutorial about the sample app at the
    <a href="https://www.railstutorial.org/contact">contact page</a>.
</p>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
  <h1>
    Welcome to Spreedly Airlines 
  </h1>

  <%= link_to image_tag("logo_b.png", alt: "Spreedly logo"), root_path, class: "header-logo" %>
  
  <form id="payment-form" action="/result">
    <input type="hidden" name="payment_method_token" id="payment_method_token">
    <input type="hidden" name="full_name" id="full_name">
    <input type="hidden" name="month" id="month">
    <input type="hidden" name="year" id="year">
    <input type="button" value="Enter Payment Info" onclick="SpreedlyExpress.openView();">
  </form>

  <%# <h2>
    This is the home page for the
    <a href="https://www.railstutorial.org/">Ruby on Rails Tutorial</a>
    sample application.
  </h2> %>

  <%# <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary"  %>
</div>

<script>
  SpreedlyExpress.init("PdP9T8axLXYKeyA8H5K8moP5c2W", {
    "amount": "$9.83",
    "company_name": "Acme Widgets"
  });

  SpreedlyExpress.onPaymentMethod(function(token, paymentMethod) {

    // Send requisite payment method info to backend
    var tokenField = document.getElementById("payment_method_token");

    tokenField.setAttribute("value", token);

    var masterForm = document.getElementById('payment-form');
    masterForm.submit();
  });

  let handlePaymentToken = function(token, formData) {
    document.getElementById('full_name').value = formData["full_name"]
    document.getElementById('month').value = formData["month"]
    document.getElementById('year').value = formData["year"]
    document.getElementById('payment_method_token').value = token
    document.getElementById('payment-form').submit();
  }
  SpreedlyExpress.onPaymentMethod(handlePaymentToken);
</script>

<%# <%= link_to image_tag("rails.png", alt: "Rails logo"),
            'http://rubyonrails.org/' %>

app/views/static_pages/result.html.erb
<% provide(:title, "Result") %>
<h1>Result</h1>
<h1>Spreedly Express success</h1>
<p>  Spreedly Express successfully added a payment token to the sample form. </p>
<p> The sample form was submitted successfully!!! </p>

<h3>Parameters Submitted From Master Form</h3>
<ul id="parameters">
</ul>
<br/>
<a href="/">Back to basic example</a>

<br/><br/><br/>
<%= @parsed_purchase_response %>

<script>
  function getParameterByName(name) {
    name = name.replace(/[\[]/, "\\[").replace(/[\]]/, "\\]");
    var regex = new RegExp("[\\?&]" + name + "=([^&#]*)"),
      results = regex.exec(location.search);
    return results == null ? "" : decodeURIComponent(results[1].replace(/\+/g, " "));
  }
  var params = ['payment_method_token', 'full_name', 'month', 'year']
  var ul = document.getElementById('parameters');
  for(var i = 0; i < params.length; i++) {
    li = document.createElement('li');
    var param = params[i];
    li.innerHTML = param + ': ' + getParameterByName(param);
    ul.appendChild(li);
  }
</script>

app/views/transactions/_form.html.erb
<h3>Create a Transaction</h3>
 
<%= form_for [ @flight, @transaction ] do |f| %>
  <p>
    <%= f.label :transaction_token %><br/>
    <%= f.text_field :transaction_token %>
  </p>
  <p>
    <%= f.label :total_price %><br/>
    <%= f.number_field :total_price %>
  </p>
  <p>
    <%= f.submit 'Submit' %>
  </p>
<% end %>

app/views/transactions/create.html.erb
<h1>Transactions#create</h1>
<p>Find me in app/views/transactions/create.html.erb</p>

app/views/transactions/index.html.erb
<div class="center jumbotron">

  <h2>All transactions:</h2>
  
  <ul id="transactions">
    <% @transactions.each do |transaction| %>
      <li>
        Created At: <%= transaction.created_at %> | 
        Transaction Token: <%= transaction.transaction_token %> | 
        Total Charge: $<%= transaction.total_price %>
      </li>
    <% end %>
  </ul>

</div>

app/views/transactions/new.html.erb
<h2>Selected Flight</h2>

<table>
  <tr>
    <th>Origin  |</th>
    <th>Destination  |</th>
    <th>Flight Price  |</th>
    <th>Total Price</th>
  </tr>

  <tr>
    <td><%= @flight.origin %></td> 
    <td><%= @flight.destination %></td>
    <td>$<%= @flight.price %></td>
    <td>$<%= @total_price %></td>
  </tr>
</table><br><br>

<form action="/flights/<%= @flight.id %>/transactions/new" id="payment-form">
  <input type="hidden" name="payment_method_token" id="payment_method_token">
  <input type="hidden" name="total_charge" id="total_charge" value=<%= @total_price %>>
  <input type="checkbox" name="save_card" value="true" checked> Save card for future use?<br>
  <input type="button" value="Checkout" onclick="SpreedlyExpress.openView();">
</form>

<script>
  // Initialize Spreedly Express with total cost
  SpreedlyExpress.init("<%= @environment_key %>", {
    // Additional quotation marks are needed for this to resolve as a string
    "amount": "<%= "$#{@total_price}" %>",
    "company_name": "Spreedly Airlines"
  });
  // Create a callback function that sends the payment method token to company servers
  SpreedlyExpress.onPaymentMethod(function(token, paymentMethod) {
    // Send requisite payment method info to backend
    var tokenField = document.getElementById("payment_method_token");
    tokenField.setAttribute("value", token);
    var masterForm = document.getElementById('payment-form');
    masterForm.submit();
  });
</script>

app/views/transactions/show.html.erb
<h1>Transactions#show</h1>
<p>Find me in app/views/transactions/show.html.erb</p>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
  </aside>
</div>